# Generated by Django 3.1.1 on 2020-09-05 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_phoneotp_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="phone number must enter in format: '+999999999'. up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
