# Generated by Django 3.1.1 on 2020-09-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20200910_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='count_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='count_internet',
            field=models.IntegerField(null=True),
        ),
    ]
