# Generated by Django 3.1.1 on 2020-09-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20200910_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
